### ISSUE TITLE
Do not set lastHeartbeat field automatically when exchange node resource is created

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/exchange-api#429]
The problem is that if the node resource is pre-created via the `hzn` CLI or UI (i.e. **not** by the agent), the presence of a `lastHeartbeat` value makes it looks like the agent on the edge node is active, when in reality it hasn't even been installed yet. This is the normal flow for SDO edge devices, and causes the UI to show the node as `Unregistered` when it should show it as `Inactive`.

Also see the comment below by @dlarson04 to add a similar option to `PUT /orgs/{orgid}/nodes/{nodeid}/agreements/<ag_id>`

The fix needs to be a joint effort between the exchange and anax squads:

- **Exchange:** Add an optional parameter (after ? in the URL) called `noheartbeat` on `PUT /orgs/{orgid}/nodes/{nodeid}` and `PUT /orgs/{orgid}/nodes/{nodeid}/agreements/<ag_id>` . If this is set to `true` do automatically update the `lastHeartbeat` field during the API.
    - Notes:
        - Need to still be able to do both things in a single REST API for the agent for scalability.
        - Continue to always set `lastUpdated` on both of these APIs`
- **Agent:** The agent work for this issue was moved to : https://github.com/open-horizon/anax/issues/2193

**Comment by sf2ne** [comment]
Do this before issue #419

**Comment by dlarson04** [comment]
The heartbeat is also set on a call to `PUT node/<id>/agreements/<ag_id>` but IMO this is unnecessary as the agent has to invoke the `/changes` route which sets the heartbeat in order to know that the agbot wants to form an agreement.  Bruce's idea was to add the same mechanism to the agent to avoid the heartbeat in this API call.  In this scenario, I would like the agent to set the parameter so the exchange does NOT  set the heartbeat  when it forms agreements.

I will update the comment in [open-horizon/anax#2193](https://github.com/open-horizon/issues/2193)

**Comment by bmpotter** [comment]
This update is ready to use in image `openhorizon/amd64_exchange-api:2.59.0` .
