### ISSUE TITLE
URL parameters don't seem to be passed in

### ISSUE THREAD

**Issue by cgiroua** [open-horizon/exchange-api#77]
Executing a curl to the exchange with URL parameters (Like the Swagger UI does) seems to drop the parameters:

See the following curl/response:
`curl -X GET "https://exchange.staging.bluehorizon.network/v1/orgs?id=bogusorg%2bogususer&token=bogustoken" -H  "accept: application/json"`
`{
  "code": "invalid-credentials",
  "msg": "no credentials given"
}`

**Comment by bmpotter** [comment]
From my testing and examination of the code, this problem only occurs in these 2 cases:
1. Querying `/orgs`
1. Using root credentials

This is fixed in exchange version 1.60.0. But you have a problem in your curl cmd: missing the `F` in the separator code. It should be `id=bogusorg%2Fbogususer`. Alternatively, you can put in the slash directly: `id=bogusorg/bogususer`. And in every other case beside querying `/orgs`, if you specify `id=bogususer` it will add the org to the front automatically.
